CUDA_VISIBLE_DEVICES=2 \
python original repo(路径已修改)\train_beam_retriever.py \
--do_train \
--gradient_checkpointing \
--prefix \
train_2wiki_continue_training \
--model_name \
MoritzLaurer/deberta-v3-large-zeroshot-v2.0 \
--tokenizer_path \
MoritzLaurer/deberta-v3-large-zeroshot-v2.0 \
--train_file \
datasets/mrc/2wikimultihop/data/train.json \
--predict_file \
datasets/mrc/2wikimultihop/data/dev.json \
--train_batch_size \
8 \
--learning_rate \
1e-5 \
--fp16 \
--beam_size \
1 \
--predict_batch_size \
1 \
--mean_passage_len \
120 \
--warmup-ratio \
0.1 \
--log_period_ratio \
0.01 \
--accumulate_gradients \
8 \
--eval_period_ratio \
0.3